# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import videocapture.models
import videocapture.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='The video to uploading to the site. Not editable after upload.', upload_to=videocapture.models.video_upload_location, validators=[videocapture.validators.validate_file_extension])),
                ('title', models.CharField(help_text='Title for the video. This is editable after upload.', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False, unique=True)),
                ('dateFilmed', models.DateField(help_text='The date when this video was filmed. Not editable after upload.')),
            ],
        ),
    ]
